### ISSUE TITLE
Readme install has to be changed

### ISSUE THREAD

**Issue by alperozisik** [smartface/sf-extension-barcode#1]
Readme install has to be like this
```shell
(cd ~/workspace/scripts && npm i -S sf-extension-barcode
```

require example has to be like this:
```javascript
var BarcodeScanner = require("sf-extension-barcode");
```

**Comment by hasretsariyer** [comment]
I changed installation command. Require style is ok because we will add new feature in next version.

**Comment by ozcanovunc** [comment]
Documentation has been updated
